name: Ticket Checker

on: 
  schedule:
    - cron: '*/1 * * * *'  # 15분마다 실행
  workflow_dispatch:

jobs:
  ticket-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run ticket checker
        run: python check_ticket.py
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
